//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKZAMEN1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> ScoreStory { get; set; }
        public Nullable<int> ScoreActing { get; set; }
        public Nullable<int> ScoreVisuals { get; set; }
        public string Comment { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual User User { get; set; }
    }
}
